{% set name = "augurs" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/augurs-{{ version }}.tar.gz
  sha256: fc86a74950c55372f98e07825a48715133fd8b97f9846cd5a7bba6525946acf1

build:
  skip: True  # [py<37]
  script:
      - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
      - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - python
    - maturin >=1.0,<2.0
    - pip
  run:
    - python
    - numpy

test:
  imports:
    - augurs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/grafana/augurs
  dev_url: https://github.com/grafana/augurs/tree/main/crates/pyaugurs
  summary: Python bindings for the augurs time series library.
  license: MIT AND Apache-2.0
  license_file:
    - THIRDPARTY.yml
    - crates/augurs-changepoint/LICENSE-APACHE
    - crates/augurs-changepoint/LICENSE-MIT
    - crates/augurs-clustering/LICENSE-APACHE
    - crates/augurs-clustering/LICENSE-MIT
    - crates/augurs-core/LICENSE-APACHE
    - crates/augurs-core/LICENSE-MIT
    - crates/augurs-dtw/LICENSE-APACHE
    - crates/augurs-dtw/LICENSE-MIT
    - crates/augurs-ets/LICENSE-APACHE
    - crates/augurs-ets/LICENSE-MIT
    - crates/augurs-forecaster/LICENSE-APACHE
    - crates/augurs-forecaster/LICENSE-MIT
    - crates/augurs-mstl/LICENSE-APACHE
    - crates/augurs-mstl/LICENSE-MIT
    - crates/augurs-outlier/LICENSE-APACHE
    - crates/augurs-outlier/LICENSE-MIT
    - crates/augurs-prophet/LICENSE-APACHE
    - crates/augurs-prophet/LICENSE-MIT
    - crates/augurs-seasons/LICENSE-APACHE
    - crates/augurs-seasons/LICENSE-MIT
    - crates/augurs-testing/LICENSE-APACHE
    - crates/augurs-testing/LICENSE-MIT
    - crates/pyaugurs/LICENSE-APACHE
    - crates/pyaugurs/LICENSE-MIT

extra:
  recipe-maintainers:
    - thewchan
